FROM ubuntu:precise

RUN apt-get update
RUN apt-get install -y curl aptitude software-properties-common python-software-properties
RUN apt-get install -y less
RUN add-apt-repository ppa:fkrull/deadsnakes
# RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.5-dev
RUN curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
RUN python3.5 get-pip.py

COPY requirements /src/requirements
RUN pip install -r /src/requirements/test.txt
RUN pip install -r /src/requirements/build.txt

COPY main.py /src
COPY s3sync /src/s3sync

# Tests
RUN cd /src; coverage run -m unittest discover
RUN cd /src; coverage report --skip-covered

# Build
RUN cd /src ; pyinstaller --hidden-import configparser --onefile -n s3sync main.py
