from prometheus_client import Gauge


source_files = Gauge('s3sync_source_files', 'Number of source files.', ['include'])
source_bytes = Gauge('s3sync_source_bytes', 'Size of source files in bytes.', ['include'])
destination_files = Gauge('s3sync_destination_files', 'Number of destination files.', ['include'])
destination_bytes = Gauge('s3sync_destination_bytes', 'Size of destination files in bytes.', ['include'])
queue_files = Gauge('s3sync_queue_files', 'Number of queued files.', ['include'])
queue_bytes = Gauge('s3sync_queue_bytes', 'Size of queued files in bytes.', ['include'])
transferred_files = Gauge('s3sync_transferred_files', 'Number of transferred files.', ['include'])
transferred_bytes = Gauge('s3sync_transferred_bytes', 'Size of transferred files in bytes.', ['include'])
source_total_files = Gauge('s3sync_source_total_files', 'Number of total source files.')
source_total_bytes = Gauge('s3sync_source_total_bytes', 'Size of total source files in bytes.')
destination_total_files = Gauge('s3sync_destination_total_files', 'Number of total destination files.')
destination_total_bytes = Gauge('s3sync_destination_total_bytes', 'Size of total destination files in bytes.')
queue_total_files = Gauge('s3sync_queue_total_files', 'Number of total queued files.')
queue_total_bytes = Gauge('s3sync_queue_total_bytes', 'Size of total queued files in bytes.')
transferred_total_files = Gauge('s3sync_transferred_total_files', 'Number of total transferred files.')
transferred_total_bytes = Gauge('s3sync_transferred_total_bytes', 'Size of total transferred files in bytes.')
rescan_files = Gauge('s3sync_rescan_files', 'Number of rescan files: should be zero most of the time.')
errors = Gauge('s3sync_errors', 'Number of errors.', ['type'])
